### ISSUE TITLE
UC Davis Health users are being put into the Cancer Center and should be merged with UC Davis

### ISSUE THREAD

**Issue by bofstein** [CDLUC3/dmptool#739]
Currently, users with @health.ucdavis.edu emails are being added to the UCD Comprehensive Cancer Center because that matches the ROR website, but this is outdated, and the admins of UC Davis need to be the admins of all UC Davis + UC Davis Health.  We need to merge all of the following organizations into the single org `University of California, Davis (ucdavis.edu)` which is the one managed one:

- `Uc Davis`
- `University Of California Davis`
- `UC Davis Comprehensive Cancer Center (health.ucdavis.edu)`
- `UC Davis Health System (ucdmc.ucdavis.edu)`
- `University of California Davis Medical Center (http://ucdmc.ucdavis.edu)`

Note that some of them have RORs of sub-organizations that we should strip so that ideally they don't recreate in the tool.

Additionally, we need to add logic to direct all @health.ucdavis.edu emails into this combined UC Davis organization, in addition to the @ucdavis.edu emails already going there.  They use the same SSO as @ucdavis.edu and have the same admins and templates, even at the health organizations.

Other Notes:
- We can leave the NCST organization separate, as no one uses that as an email domain anyways and it is a separate org
- There is a single org called `Center For Companion Animal Health Uc Davis` with no plans or users we can probably delete
- `ucdmc.ucdavis.edu` is an older domain not used anymore, so we do not need logic to look for those emails, though its fine if they do get sorted in just in case of a very old email still in used.
- There are requests to ROR out to updates these records, updating many to use the consolidated health.ucdavis.edu domain.  
-- https://github.com/ror-community/ror-updates/issues/25452
-- https://github.com/ror-community/ror-updates/issues/25453
-- https://github.com/ror-community/ror-updates/issues/25450
-- https://github.com/ror-community/ror-updates/issues/25475

**Comment by bofstein** [comment]
This can be combined with #738 for release, ideally within 2 weeks but if not we just need to let the admins know when it will come out.

**Comment by bofstein** [comment]
Note that I recently changed the main managed org to have the (ucdavis.edu) domain in the name, as it didn't before which caused some lists in the tool to show a duplicate with the ROR record.  The orgs match names on Stage and Prod.  I didn't do the merge myself since I believe that needs to be done alongside the logic change to not immediately recreate the alternate orgs like with txstate.

**Comment by briri** [comment]
Ok, in Prod I already did the following to clean up some orgs:
- Merged id: 10401, "Uc Davis" into id: 7, "University of California, Davis (ucdavis.edu)" (just moved a couple of users)
- Merged id: 12396, "University of California Davis" into id: 7, "University of California, Davis (ucdavis.edu)" (just moved a couple of users)
- Deleted id: 12197, "Center For Companion Animal Health Uc Davis") (had no users, plans, templates, etc.)

I deployed the code changes to stage. Users creating accounts with email domains of: "ucdmc.ucdavis.edu", "health.ucdavis.edu" will be directed to UCD SSO and then attached to id: 7, "University of California, Davis (ucdavis.edu)". 

There are some users attached to the "health" orgs. They do not have access to the UCD templates or guidance. Do we need to move them to the UCD org? (id: 7, "University of California, Davis (ucdavis.edu)")?
- 4 users from id: 10079, "UC Davis Health System (ucdmc.ucdavis.edu)" 
- 9 users from id: 14991, "UC Davis Comprehensive Cancer Center (health.ucdavis.edu)"

If you can have one final look @bofstein I would appreciate it. If all looks good I can deploy to prod today or tomorrow morning.

**Comment by bofstein** [comment]
@briri yes we want to move those existing health org users to UCD please.  I'll confirm on Stage again today.

**Comment by bofstein** [comment]
@briri the sign-up logic looks good but I still see the orgs on the list in Stage.  Is that something you want me to Merge all those into UCD or something you do?  I don't mind doing it but thought you would have to do something special in the backend to unlink the ROR for some that you did for TXST so they didn't re-appear.

This is good to go to Prod if you either do the merge or tell me to.

<img width="645" height="615" alt="Image" src="https://github.com/user-attachments/assets/915a6ac1-ded9-4a1a-920a-7563b5336036" />

**Comment by bofstein** [comment]
I re-read your earlier comment and maybe merging them doesn't matter on Stage if you did it on Prod.  But I see the orgs on Prod still it would be nice to remove so that only the main Davis account appears in list, unless we can't get rid of that due to ROR.

<img width="712" height="618" alt="Image" src="https://github.com/user-attachments/assets/066f3ab1-1f0e-42ff-9a94-acb3cac21fd3" />

**Comment by briri** [comment]
Yeah, we can't remove them. They're active organizations in ROR and the user's true affiliations. 

We're doing this work to accommodate a flaw in the application (get everyone on the same SSO and access to templates/guidance, etc.) they'd ideally use their real organizations so that we have accurate affiliation information in the DMP metadata. 

We can prioritize creating org hierarchy in the new system after launch.
